### ISSUE TITLE
bug: `session` type issue on NextJs 12.3.0

### ISSUE THREAD

**Issue by zunnur-trinovik** [t3-oss/create-t3-app#412]
### Provide environment information

System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-1240P
    Memory: 1.77 GB / 15.69 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD

### Describe the bug

`session` not longer work and show error `Property 'session' does not exist on type '{}'` on file `_app.tsx`. " after updating the nextjs from 12.2.5 to 12.3.

![image](https://user-images.githubusercontent.com/103472495/189257927-4fc05955-42c8-4d01-9691-5c4af10b712e.png)

### To reproduce

run `npm i next@latest` which will update the next package to 12.3.0

### Additional information

Here what I found that have been changed in `utils.d.ts`.

pageProps before update:
`export declare type AppInitialProps = {
    pageProps: any;
};`

pageProps after update:
`export declare type AppInitialProps<P = any> = {
    pageProps: P;
};`

**Comment by nexxeln** [comment]
Yup I noticed this in the new next js version. I think they messed up their AppType.

**Comment by juliusmarminge** [comment]
Don't think this is on us just yet (we don't install Next 12.3 for you)

I pulled an issue on Next.js so we'll see what thry say first: https://github.com/vercel/next.js/issues/40371

**Comment by balazsorban44** [comment]
For context, `AppType` hasn't officially been exported, so this was not a bug, but I opened a PR to properly expose it and fix the underlying issue at the same time. You can follow: https://github.com/vercel/next.js/pull/40391

**Comment by leerob** [comment]
Thanks for raising this! And thank you @balazsorban44 for the quick PR.

**Comment by juliusmarminge** [comment]
https://github.com/vercel/next.js/pull/40391 just got merged so I think we can close this one and just hold off with updating until Next 12.3.1 comes out 👍🏼
