### PR TITLE
fix: do not use internal Next.js types

### LINKED ISSUE #412: bug: `session` type issue on NextJs 12.3.0
### Provide environment information

System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-1240P
    Memory: 1.77 GB / 15.69 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD

### Describe the bug

`session` not longer work and show error `Property 'session' does not exist on type '{}'` on file `_app.tsx`. " after updating the nextjs from 12.2.5 to 12.3.

image

### To reproduce

run `npm i next@latest` which will update the next package to 12.3.0

### Additional information

Here what I found that have been changed in `utils.d.ts`.

pageProps before update:
`export declare type AppInitialProps = {
    pageProps: any;
};`

pageProps after update:
`export declare type AppInitialProps<P = any> = {
    pageProps: P;
};`

### PR DESCRIPTION
**Pull request by balazsorban44**
Closes #412

As explained in https://github.com/vercel/next.js/issues/40371#issuecomment-1241805459

## ✅ Checklist

- [ ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [ ] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I performed a functional test on my final commit

---

## Changelog

_[Short description of what has changed]_

---

## Screenshots

_[Screenshots]_

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
You think this will ship in 12.3.1? https://github.com/vercel/next.js/pull/40391

I personally prefer that so much more

**Comment by c-ehrlich** [comment]
I would also prefer waiting it out for Next to solve this, or at least waiting a few days to see what happens to the PR.

**Comment by balazsorban44** [comment]
Yep, closing this PR for now. :+1: Keep an eye on https://github.com/vercel/next.js/pull/40391 and feel free to PR here when that is merged.
